### ISSUE TITLE
Mention 기능 추가

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/Xlack-Frontend#13]
### Mention 기능 추가 의견
**Rules**
- 기존 진행 중인 컨벤션 (코딩 스타일) 따라가기
- TDD
- 나중에 알림 기능도 같이 추가할 예정이므로 염두하고 구현하기
- Mention은 언급하여 댓글을 달거나 메세지를 보내는 것 입니다.

**백엔드와 프론트엔드가 함께 구현해야 하는 기능입니다. 금요일 회의에서 얘기해보고 정할 예정입니다.**
(참고 자료)
 [https://codesandbox.io/examples/package/react-mentions](url)
 [https://github.com/signavio/react-mentions](url)

**TODO:**
- [x] Front-end에서 누구와 협업 할지 정하기.
- [ ] UI 방향 설정 & 구체화
- [ ] Chat 기능에서만 Mention을 할 것인지 정하기.
- [ ] DB 연결이 필요하므로 방법 모색
